# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: indicators

# Describe your paths here
paths:
  /users:
    post:
      description: |
        Create user
      parameters:
        -
          name: email
          in: formData
          description: User's email
          required: true
          type: string
          format: string
        -
          name: password
          in: formData
          required: true
          description: User's password
          type: string
          format: string
        -
          name: role
          in: formData
          required: true
          description: User's role
          type: integer
        -
          name: name
          in: formData
          required: false
          description: User's name
          type: string
        - 
          name: last_name
          in: formData
          required: false
          description: User's last name
          type: string
        - 
          name: X-User-Access-Token
          in: header
          required: true
          description: User's access token
          type: string
      responses:
        200:
          description: Usuario creado correctamente
          schema:
            type: object
    get:
      description: |
        Users list
      parameters:
        -
          name: X-User-Access-Token
          in: header
          required: true
          description: Current user's oauth token
          type: string
      responses:
        200:
          description: asdas
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
            
              
      
definitions:
  User:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
      role: 
        enum: [1, 2, 3, 4, 5]
        type: integer
      name: 
        type: string
      last_name:
        type: string
      X-User-Access-Token:
        type: string
  Establishment:
    type: object
    properties:
      name:
        type: string
      state:
        type: boolean
      crea_group:
        $ref: '#/definitions/CreaGroup'
      coneat:
        type: integer
      location:
        type: object
        properties:
          latitude: 
            type: number
            format: float
          longitude:
            type: number
            format: float
      share_fucrea:
        type: boolean
      share_group:
        type: boolean
  CreaGroup:
    type: object
    properties:
      name: 
        type: string
  